version: "3.9"

services:
  db:
    image: postgres:15
    container_name: osint_db
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: osint_adminer
    depends_on:
      - db
    environment:
      - TZ=${TZ}
    ports:
      - "8080:8080"

  ingestion:
    build: ./ingestion
    container_name: osint_ingestion
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./ingestion:/app
    depends_on:
      db:
        condition: service_healthy
    command: ["bash", "-lc", "scrapy crawl brookings -s LOG_LEVEL=INFO"]

  nlp:
    build: ./nlp
    container_name: osint_nlp
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./nlp:/app
    depends_on:
      db:
        condition: service_healthy
    command: ["bash"]

  dashboard:
    build: ./dashboard
    container_name: osint_dashboard
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./dashboard:/app
      - ./nlp:/app/nlp:ro
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8501:8501"

volumes:
  db_data:
